### DISCUSSION TITLE
Am I missing something or it's a bug?

### DISCUSSION THREAD

**Discussion by ivancarlosti** [upptime/upptime#1010] [Q&A]
I am looking to monitor specific httpcodes, I preffer that way because a compromissed domain or website can remains online but reporting different status.

For alias domains I like to monitor the 301 httpstatus, but for a specific domain it return httpcode 301 on browser, but Upptime reports statuscode 200. As I configured to only check for status 301, it reports that the website is down.

The domain I am testing is https://sp4com.com.br and looking for it on https://httpstatus.io/ and https://www.redirect-checker.org/ bot reports status 301.

Code:
```
  - name: SP4.sp4com
    url: https://sp4com.com.br
    expectedStatusCodes:
      - 301
 ```

Please, what am I missing?

Thanks and regards
