### DISCUSSION TITLE
Possible to have multiple strings for custom status detection?

### DISCUSSION THREAD

**Discussion by ReenigneArcher** [upptime/upptime#1032] [Q&A]
e.g.

https://upptime.js.org/docs/configuration/#custom-status-detection
```yml
sites:
  - name: Custom down
    url: https://example.com
    __dangerous__body_degraded:
      - "status: degraded"
      - "status: unknown"
```
