### DISCUSSION TITLE
Check for request response body match

### DISCUSSION THREAD

**Discussion by kescherCode** [upptime/upptime#157] [Ideas] [answered]
Currently, we can only check for an exact body to consider a fail.
However, some of my monitored services have their own internal monitoring, which would make it easy to report if something in the body does NOT match the expected sane values.

**Comment by AnandChowdhary** [comment]
So, you're saying, like we can use `__dangerous__body_down` to check if something is in the body and mark the site as down:

```yaml
sites:
  - name: Custom down
    url: https://example.com
    __dangerous__body_down: "File not found"
```

We can do `__dangerous__body_down_if_text_missing`:

```yaml
sites:
  - name: Custom down
    url: https://example.com
    __dangerous__body_down_if_text_missing: "Everything looks good"
```

In the above example, if the body doesn't include the text "Everything looks good", we'll mark the site as down. Is this right? Happy to add this feature.

**Comment by kescherCode** [comment]
Yes, this is exactly what I had in mind ^^

**Comment by AnandChowdhary** [comment, marked as answer]
Done, this has been added in [@upptime/uptime-monitor@v1.24.0](https://github.com/upptime/uptime-monitor/releases/tag/v1.24.0):

```yaml
sites:
  - name: Custom down
    url: https://example.com
    __dangerous__body_down_if_text_missing: "Everything looks good"
    __dangerous__body_degraded_if_text_missing: "Everything is fast"
```
