### DISCUSSION TITLE
Support i18n status on README

### DISCUSSION THREAD

**Discussion by annkuoQ** [upptime/upptime#161] [Ideas] [answered]
On the overall summary of README.
[i18n.yml](https://github.com/upptime/status-page/blob/cc5b8c496f9aa605314b021e3c77e030f8b60be0/i18n.yml#L2) only support `All systems are operational`.
but `Degraded performance`, `Partial outage`, `Complete outage` not support.

**Comment by AnandChowdhary** [comment, marked as answer]
It actually does, but it's not documented yet. 😢 I'll make sure I update the template file! Currently, the `i18n.yml` file only has the keys for the status website, but these missing ones are also supported for the README:

```yaml
i18n:
  url: "URL"
  status: "Status"
  history: "History"
  responseTime: "Response Time"
  uptime: "Uptime"
  up: "🟩 Up"
  degraded: "🟨 Degraded"
  down: "🟥 Down"
  responseTimeGraphAlt: "Response time graph"
  ms: "ms"
  responseTime: "Response time"
  responseTimeDay: "24-hour response time"
  responseTimeWeek: "7-day response time"
  responseTimeMonth: "30-day response time"
  responseTimeYear: "1-year response time"
  uptime: "All-time uptime"
  uptimeDay: "24-hour uptime"
  uptimeWeek: "7-day uptime"
  uptimeMonth: "30-day uptime"
  uptimeYear: "1-year uptime"
  liveStatus: "Live Status"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "🟩 All systems operational"
  degradedPerformance: "🟨 Degraded performance"
  completeOutage: "🟥 Complete outage"
  partialOutage: "🟧 Partial outage"
```
