### DISCUSSION TITLE
How to setup own emojis?

### DISCUSSION THREAD

**Discussion by ririko5834** [upptime/upptime#207] [Q&A]
Hello, how can I setup my own emojis for issues and notifications?
![image](https://user-images.githubusercontent.com/64729293/104308233-a26e4b00-54d0-11eb-924b-1fe8eec83ba2.png)
![image](https://user-images.githubusercontent.com/64729293/104308273-adc17680-54d0-11eb-88fe-ce03a6bcc103.png)

**Comment by ririko5834** [comment]
When I set this
```
i18n:
  up: "✅ Up"
  degraded: "⚠️ Degraded"
  down: "🚨 Down"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "✅ All systems operational"
  degradedPerformance: "⚠️ Degraded performance"
  completeOutage: "🚨 Complete outage"
```
it will not work, the original emojis will be still there :/
![image](https://user-images.githubusercontent.com/64729293/104438469-508cfa00-5590-11eb-8928-6973588f7b0f.png)
