### DISCUSSION TITLE
Dark Theme Support

### DISCUSSION THREAD

**Discussion by FxllenCode** [upptime/upptime#209] [Ideas] [answered]
Currently, upptime sites are solely in light theme:

![image](https://user-images.githubusercontent.com/40151425/104388328-f7c54f00-5506-11eb-9f42-ae2168619074.png)

While it looks great, it's very bright. Going from any code editor to that is a huge change:

![MHBxJTfYqr](https://user-images.githubusercontent.com/40151425/104388509-45da5280-5507-11eb-8083-efe8dec74339.gif)

These days most sites give the user the option; it's better UX. I feel we should be able to configure this so our site can support dark theme; I could see an issue with our users going from a dark theme site to this, it would look very displeasing.

This would be a great feature, especially with [this ](https://github.com/upptime/upptime/discussions/206)and [this](https://github.com/upptime/upptime/discussions/201). 

Thanks! 🙂

**Comment by ririko5834** [comment]
Good idea

**Comment by AnandChowdhary** [comment, marked as answer]
Support for themes has been added in [`upptime/status-page@v1.8.0`](https://github.com/upptime/status-page/releases/tag/v1.8.0). Theme can be `light`, `dark`, or `ocean`:

```yaml
status-page:
  theme: "light"
```

| Dark | Ocean |
| - | - |
| ![Screen Shot 2021-01-22 at 20 14 22](https://user-images.githubusercontent.com/2841780/105506420-09b9a580-5cf0-11eb-81d3-2c84f3b945d8.png) | ![Screen Shot 2021-01-22 at 20 16 25](https://user-images.githubusercontent.com/2841780/105506404-045c5b00-5cf0-11eb-89f8-c50ab2f7f98e.png) |

You can create your own themes using CSS variables, using [`dark.css`](https://github.com/upptime/status-page/blob/v1.8.0/static/themes/dark.css), for example as a starting point:

```css
:root {
  --body-background-color: #001716;
  --body-text-color: #f0ffff;
  --card-background-color: #002b29;
  --nav-background-color: #002b29;
  --nav-border-bottom-color: #015450;
}
/* . . . */
```
