### DISCUSSION TITLE
Parse status from JSON file

### DISCUSSION THREAD

**Discussion by tmeuze** [upptime/upptime#216] [Q&A]
Hi, this is my first time attempting something of this sort; I don't have much experience in this field. I would like to monitor a service which reports their status in the form of a JSON file. I would like use Upptime to retrieve this file, then query a specific property for its value. Beyond that, I believe I could use expectedStatusCodes to display the appropriate status. 

The particular service in question has its status JSON available here: https://status.ringcentral.com/status.json . In this example, I would want to scope (?) a particular array, then read the value of "level".

Is such a use of Upptime possible? If so, I'd be grateful if someone can explain a configuration that would achieve this. 

Thank you,

EDIT: This is the configuration I have so far:

```
  - name: RingCentral
    method: GET
    url: https://status.ringcentral.com/status.json
    headers:
      - "Content-Type: application/json"
```

Perhaps there are some undocumented options that will allow this?
