### DISCUSSION TITLE
robots.txt or meta tag

### DISCUSSION THREAD

**Discussion by pearanalytics** [upptime/upptime#222] [Q&A] [answered]
Is there a simple way to add a robots.txt file to status site that's created in which we can tell Google not to index anything on the subdomain? Or add the following meta tag to the pages? 
```
<meta name="robots" content="noindex, nofollow">
```

**Comment by FxllenCode** [comment]
Good question! I've had this too, we can add custom CSS and JS but we cannot add HTML. (AFAIK). This would be a great feature, it should probably be re-written as a feature request however.

**Reply by AnandChowdhary** [reply]
All done!

**Comment by AnandChowdhary** [comment, marked as answer]
This has been added in [`upptime/status-page@v1.8.0`](https://github.com/upptime/status-page/releases/tag/v1.8.0). You can specify the `robotsText` string:

```yaml
status-page:
  robotsText: "User-agent: * \n Disallow: /"
```

This will generate and deploy a `robots.txt` file on your status website.

**Comment by AnandChowdhary** [comment]
I've also added support for custom HTML and custom meta tags in [upptime/status-page@v1.9.0](https://github.com/upptime/status-page/releases/tag/v1.9.0):

```yaml
status-website:
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  customHeadHtml: "<!-- any custom HTML to append in <head> -->"
  customBodyHtml: "<!-- any custom HTML to append at the top of <body> -->"
```
