### DISCUSSION TITLE
How can I setup custom html?

### DISCUSSION THREAD

**Discussion by ririko5834** [upptime/upptime#227] [Q&A] [answered]
How can I setup custom html for my statuspage?
I want to add there META HTML tags.

**Comment by AnandChowdhary** [comment, marked as answer]
I've added support for custom HTML and custom meta tags in [upptime/status-page@v1.9.0](https://github.com/upptime/status-page/releases/tag/v1.9.0):

```yaml
status-website:
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  customHeadHtml: "<!-- any custom HTML to append in <head> -->"
  customBodyHtml: "<!-- any custom HTML to append at the top of <body> -->"
```

**Reply by ririko5834** [reply]
Thanks, you should update docs. 
Also how can I config my own emojis?

**Reply by AnandChowdhary** [reply]
Docs are updated!

By emoji, I think you mean the emoji we use to show "down", "degraded", or "up", right? If that's the case, you can update them using the internationalization option:

```yaml
i18n:
  allSystemsOperational: "🟩 All systems operational"
  degradedPerformance: "🟨 Degraded performance"
  completeOutage: "🟥 Complete outage"
  partialOutage: "🟧 Partial outage"
```

Here, you can keep the text same while updating the emoji.
