### DISCUSSION TITLE
Checking also non-http(s) services

### DISCUSSION THREAD

**Discussion by thomasmerz** [upptime/upptime#238] [Ideas] [answered]
Hi @AnandChowdhary , I really fell in love with this project! ❤️  
I really would appreciate to have the ability for checking non http(s) services as well. For example:  

Is anything listening on port xyz on host/IP (without result/returncode)?
```
$ tcping -t 1 8.8.8.8 53
8.8.8.8 port 53 open.
```

**Comment by AnandChowdhary** [comment]
Good idea. I think [`tcp-ping`](https://github.com/apaszke/tcp-ping) can be used for this.

**Comment by AnandChowdhary** [comment, marked as answer]
Support for pinging using [`tcp-ping`](https://github.com/apaszke/tcp-ping) has been added in [@upptime/uptime-monitor@v1.25.1](https://github.com/upptime/uptime-monitor/releases/tag/v1.25.1).

You'll need to add the property `check: "tcp-ping"` to use this:

```yaml
sites: # List of endpoints to track
  - name: Google
    check: "tcp-ping"
    url: 46.28.246.123
    port: 80
```
