### DISCUSSION TITLE
Why does it take about "many" 5-minute-cycles to get a "two-minute DOWN service" as UP again?

### DISCUSSION THREAD

**Discussion by thomasmerz** [upptime/upptime#240] [Q&A] [answered]
I have a daily update-policy for my docker-based services: Pulling, then checking if newer image has been downloaded and if this is the case: stop and start docker container. Usually this takes about less than two minute(s) (also in this case below) until "ready":

<img width="404" alt="image" src="https://user-images.githubusercontent.com/18568381/106453274-525c2600-6489-11eb-999f-f6de0196e7c7.png">

https://thomasmerz.github.io/upptime/incident/29  

`$ git log --grep Pihole-HEL`
```
…
commit b873a31e1c7664c4a48eaf5d1724d82b62ca3cbf
Author: Upptime Bot <73812536+upptime-bot@users.noreply.github.com>
Date:   Mon Feb 1 06:57:04 2021 +0000

    🟩 Pihole-HEL is up (200 in 1409 ms) [skip ci] [upptime]

commit fa4d4fe5dcd28e621680864d3b9d450a2164473e
Author: Upptime Bot <73812536+upptime-bot@users.noreply.github.com>
Date:   Mon Feb 1 06:30:18 2021 +0000

    🟥 Pihole-HEL is down (0 in 0 ms) [skip ci] [upptime]
…
```

First I thought, this might be due to my `.upptimerc.yaml`
```
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
```

But everything "important" should run every 5 minutes… 🤔 

**Q: Why does upptime need so much 5-minute cycles to determine the service as UP again?** I expected that it would has been UP within the next 5-minute cycle… (which has been indeed started again at 07:31:52 after being stopped at 07:30:11)
