### DISCUSSION TITLE
Custom Status Site

### DISCUSSION THREAD

**Discussion by flauc** [upptime/upptime#257] [Ideas] [answered]
It's currently very hard to create a custom status site from https://github.com/upptime/status-page. You would need to fork both the `status-page` and the `uptime-monitor` project. Then adjust this script `https://github.com/upptime/uptime-monitor/blob/master/src/site.ts` to use your own `status-page` project. 
Additionally you need to disable template updates and update the site workflow in your repo. 

I think this [script](https://github.com/upptime/uptime-monitor/blob/master/src/site.ts) needs to be extended to pull from a specific repo or npm library and in `.upptimerc.yml` we add something like `siteUrl` as the link from where to download the site.

**Comment by AnandChowdhary** [comment, marked as answer]
I've tried to make it somewhat easier to add a custom website.

**Method 1:** If you fork the `@upptime/status-page` project, you can create your own static site generator and publish it to npm. This expects the same `export` script present in `package.json`. It essentially replaces our project with any npm package name:

```yaml
customStatusWebsitePackage: "@upptime/status-page"
```

**Method 2:** You can completely disable generating the status website, and instead set that up yourself:

```yaml
skipGeneratingWebsite: true
```

In this case, you shouldn't edit the `site.yml` workflow (since it's auto-updated), but instead create your own GitHub Actions workflow, for example `custom-site.yml` that runs every day and generates your site however you like. I've made sure that we don't remove your custom workflows during the update process:

```yaml
name: Custom Site CI
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  release:
    name: Add custom site
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Generate site
        uses: echo "Setting up my website!"
      - uses: maxheld83/ghpages@v0.3.0
        name: GitHub Pages Deploy
        env:
          BUILD_DIR: "list"
          GH_PAT: ${{ secrets.GH_PAT }}
```
