### DISCUSSION TITLE
Ability to satisfy hostname in url

### DISCUSSION THREAD

**Discussion by SJang1** [upptime/upptime#259] [Ideas] [answered]
I think ability to satisfy hostname to check if server status, will make more great on checking the server.
on Browsers, it sends as **Host** on the header
and on curl can use like this : `curl -H "Host: www.google.com" http://172.217.164.100/`

After making it, maybe could be used like this (Main useage why I think it's needed) : 
```
  - name: Google with IP address
    url: http://172.217.164.100/
    host: www.google.com
```
or also like this : 
```
  - name: Google just with hostname
    url: http://www.google.com/
    host: www.google.com
```

**Comment by AnandChowdhary** [comment, marked as answer]
You can add a custom header since the `Host` is just a regular request header: https://upptime.js.org/docs/configuration/#request-headers

```yaml
- name: Google with hostname
  url: https://www.google.com
  headers:
    - "Host: www.google.com"
```
