### DISCUSSION TITLE
Question: How do you keep template topics in place?

### DISCUSSION THREAD

**Discussion by astrochun** [upptime/upptime#330] [General] [answered]
A while ago I used this template for our organization and it has all the topics, such as @upptime in our version.  I like what you did so I'm trying to do something for another project of mine, a template with the GitHub actions to enable easy deployment. However, with a template, those topics are lost when you use it to generate a new repo. I wonder how you managed to keep it present so you can use topics to find uses of your repo. I suspect this might be a GitHub Action but from looking at your actions, I could not find it.

**Comment by AnandChowdhary** [comment, marked as answer]
We use the Summary CI to add the repository description and topics: https://github.com/upptime/uptime-monitor/blob/master/src/summary.ts#L245.

**Reply by astrochun** [reply]
Thanks. I did later find the GitHub docs: https://docs.github.com/en/rest/reference/repos#replace-all-repository-topics

And ended up adding the following:
```
    - name: Update repository topics
      shell: bash
      env:
        URL: https://api.github.com/repos/${{ github.repository }}/topics
        TOPICS: '{"names":[,"docker",...]'
        AUTH: "Authorization: token ${{ secrets.GH_TOKEN }}"
      run: |
        curl -X PUT "$URL" -d "$TOPICS" \
          -H "Accept: application/vnd.github.mercy-preview+json" -H "$AUTH"
```
