### DISCUSSION TITLE
Add an option to automatically post downtimes and scheduled maintenances to Twitter

### DISCUSSION THREAD

**Discussion by ajhalili2006** [upptime/upptime#350] [Ideas]
## About the Problem

Let's say one of my services goes down due to the forgot-to-tenew-domain-registration-but-autorenew-is-disabled chaos and I want to notify my customers through Twitter about the downtime. But, assuming that I'm from my phone and my bot notified about about the issue, I would need to manually compose updates into Twitter.

## Proposed Solution

Maybe add some config var for Twitter autoposting like these:

```yml
# this example workflow file is WIP, will update later as I read more Twitter API docs again
# for community maintainers and Koj employees, feel free update this
variables:
    ENABLE_TWITTER_BROADCASTING: ${{ secrets.ENABLE_TWITTER_BROADCASTING || false }}
    TWITTER_API_CLIENTID: ${{ secrets.TWITTER_API_CLIENTID }}
    TWITTER_API_CLIENTSECRET: ${{ secrets.TWITTER_API_CLIENTSECRET }}
```

...and for configuring the tweet format in `.upptimerc.yml` will lool like:

```yml
# customizations for sending status messages should be also available for Slack, Telegram, etc.
# and also on per-service basis, shall we?
notifications:
   twitter:
      # issueType: either "client-server latency", "server-side issues" or "hosting provider-side problems"
      downtimeTweet: "${serviceName} is currently having some issues regarding ${issueType}. We'll tracking it on ${issueLink}."
      # this one will reply to the incident/scheduled maintenance tweet
      investigatingTweet: "We're currently investigating why ${serviceName} is having hiccups. We'll follow-up as soon as we found the culprit."
      updateTweet: "We're currently working on fixing the issue. Our engineers are actively debugging the issue. Stay tuned in this thread for more."
      fixCommitedTweet: "An fix has been commited and scheduled to be deployed into production. We'll monitor the situtation as the deployment rolls across our servers."
      fixDeployedTweet: "An fix has been deployed and we're currently tracking if the situation improves."
      resolved: "The incident has been resolved. If you want to learn more, please see ${issueLink}."
      # will cover scheduled maintenance stuff next time
```

## Any related suggestions?

* https://github.com/upptime/upptime/discussions/342 for the Twitter feed on the status page
