### DISCUSSION TITLE
Categories.

### DISCUSSION THREAD

**Discussion by PersonalDom** [upptime/upptime#385] [Ideas]
Hey there. 

Is it possible to add categories? So for example you could have a category for web assets, Servers, etc.

For .upptimerc.yml it would look something like this: 
```
sites:
 category1:
      - name: Google
        url: https://www.google.com
      - name: Wikipedia
        url: https://en.wikipedia.org
      - name: Hacker News
        url: https://news.ycombinator.com
  category2:
      - name: Minecraft
        check: "tcp-ping"
        url: 46.28.246.123
        port: 80
      - name: FiveM
        check: "tcp-ping"
        url: 46.28.246.123
        port: 80
  ```
and on the static page: (a rough photoshop edit.)
![upptime-cat-suggest](https://user-images.githubusercontent.com/65628740/121818021-a4555980-cc7c-11eb-88dc-f205998faa2c.png)
