### DISCUSSION TITLE
HELP - Uncaught (in promise) TypeError

### DISCUSSION THREAD

**Discussion by axsddlr** [upptime/upptime#391] [Q&A] [answered]
Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://rehkloos.github.io/') with script ('https://rehkloos.github.io/service-worker.js'): A bad HTTP response code (404) was received when fetching the script.

my yml

```
# Change these first
owner: Rehkloos # Your GitHub username
repo: api-status # Your GitHub repository name

sites:
  - name: General API
    url: https://api.rehkloos.com/openapi.json
    expectedStatusCodes:
      - 200
      - 204
      - 404
      - 429

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #   cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: API Status
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
```
