### DISCUSSION TITLE
GET response from JSON

### DISCUSSION THREAD

**Discussion by tmeuze** [upptime/upptime#428] [Q&A]
Is it possible for Upptime to monitor a JSON file for a change, and report the service as down?

As an example, I can use Statping to monitor the Twilio API status. The endpoint is at https://gpkpyklzq55q.statuspage.io/api/v2/summary.json , and Statping is configured as such:
![CleanShot 2021-08-11 at 12 47 49](https://user-images.githubusercontent.com/9298659/129069932-01615dec-b6ab-4a29-bb29-2a8ecabb4eae.png)

I've tried both:
```
 - name: Authy 2FA
    method: GET
    url: https://gpkpyklzq55q.statuspage.io/api/v2/summary.json
    headers:
      - "Content-Type=application/json"
    body: '("name":"Authy 2FA","status":"operational")'
```
and
```
  - name: Authy API
    method: GET
    url: https://gpkpyklzq55q.statuspage.io/api/v2/summary.json
    headers:
      - "Content-Type=application/json"
    expectedStatusCodes: 
      - '("name":"Authy 2FA","status":"operational")'
```

Am I doing something wrong, or is this just not supported?

Thank you
