### DISCUSSION TITLE
Add tags for sites

### DISCUSSION THREAD

**Discussion by gunnarvelle** [upptime/upptime#527] [Ideas] [answered]
I would like to propose adding a tags-feature to uptime. If you add tags as a array of strings to the sites property, these tags could be used to tag issues relating to the corresponding site. 

For instance if you have one test api and one production api, you could define:
```
sites:
  - name: MyApi
    url: https://api.mysite.com
    tags: production
  - name: MyApi (test)
    url: https://api.test.mysite.com
    tags: test
```
If test goes down the issue would be tagged with "test". Same goes for scheduled events. 

This would make it possible to filter the serverity of the event based on the tags. If production goes down immediate action must be made, but if test goes down it can be dealt with later.
