### DISCUSSION TITLE
Allow monitoring of other status pages

### DISCUSSION THREAD

**Discussion by Andre601** [upptime/upptime#561] [Ideas]
Sometimes a Site or service relies on another site or service to provide some of it functionality.
For example am I offering a Discord bot and therefore rely on the discord platform to be available to use.

It would therefore be a good idea to offer an option to also monitor a separate status page, if those offer some kind of API to access.

Using discordstatus as an example could I define the following entry in `sites`:

```yaml
sites:
  - name: Discord
    url: https://discordstatus.com/api/v2/status.json
    provider: statuspage-io
```

Now, upptime would check the URL and seeing that it is a JSON response would treat it as another status page to include.
The `provider` setting would help determine what type of status page this is to easier figure out the JSON scheme given by the site.

If now this site would have problems could an issue be opened informing about those external issues and - if possible - provide the current state of that site.

This is only an idea of course.
