### DISCUSSION TITLE
Add option for display name/identifier

### DISCUSSION THREAD

**Discussion by Andre601** [upptime/upptime#562] [Ideas]
Currently is the `name` option from what I get used for things such as mentioning affected sites during a scheduled maintenance.

However, people like me may use some more specific names which are weird to type out, resulting in some confusing looking names to remember.
Because of that would I like to suggest adding an option to set a different name to either display or use as the identifier.

In my example would I go with an option to display a different name on the status page, which would look like this when configured:

```yaml
sites:
  - name: images # Would be used as the identifier for scheduled maintenance
    url: https://example.com/api/img/cat
    display: Cat Images (/api/img/cat) # What should be displayed on the Status page
```

this would now use `images` as the identifier and name in stuff like labels but display `Cat Images (/api/img/cat)` in places such as the status page.
