### DISCUSSION TITLE
Allow defining custom Labels for different Statuses and sites

### DISCUSSION THREAD

**Discussion by Andre601** [upptime/upptime#563] [Ideas]
(Sorry that I suggest so many things, but they just come into mind when I write stuff down)

Right now upptime would do the following things when a site is down:

- Create an issue
- Apply labels named `status` and `<site-slug>` (i.e. `example-site`)
- Assign people (if provided)
- Lock issue

It would be a really cool feature to define your own labels to use for different states a site may have.
I can imagine two different settings here. First a general one for specific states of the site (up, down, degraded performance, etc.) and then one you can define for each individual site that would override the default label applied to the site.

Example configuration:
```yaml
labels: # Sets the labels for the different states a site can be in.
  - name: 'Status: Up' # Name for the label
    color: 0E8A16      # Hex color value for the label
    status: up         # On what status this label should be assigned
  - name: 'Status: Down'
    color: B60205
    status: down
  - name: 'Status: Degraded performance'
    color: FBCA04
    status: degraded

sites:
  - name: Example
    url: https://example.com
    labels: # Would override the default "example" label created with custom ones
      - name: 'Site: Example'
        color: 1D76DB
```

Now when the site "Example" would go down would upptime perform the following actions:

- Open new issue
- Apply labels `Status: Down` and `Site: Example` as defined by the configuration
- Assign people (if provided)
- Lock issue

Once the problem is resolved would upptime remove the `Status: Down` label and instead add the `Status: Up` to it to keep everything up to date before closing the issue.

And if we want to be REALLY fancy could there be settings to also apply labels for stuff like "Investigating" by having you comment specific phrases through HTML comments.

F.e.
```markdown
<!-- investigating -->
**Investigating:** We are looking at the issue and will report with new information shortly.
```

The `<!-- investigating -->` comment would now make upptime apply a new label `investigating` (or the one you defined) to the issue.

Some key-phrases I can think of:

- `<!-- investigating -->` for when you check the issue and what causes it.
- `<!-- monitoring -->` when you fixed it and now monitor the site for any further issues.
- `<!-- resolved -->` when the issue has been fully resolved.
