### DISCUSSION TITLE
Option of respond code to tell up

### DISCUSSION THREAD

**Discussion by SJang1** [upptime/upptime#60] [Ideas] [answered]
It's a feature request, make an option for the respond code like:
`respond_code: 101, 404` (this make 101, 404 only for up, other respond code for down)

**Comment by AnandChowdhary** [comment]
Yes, this seems like a nice feature addition!

**Comment by AnandChowdhary** [comment, marked as answer]
This is now supported. You can add the `expectedStatusCodes` array of numbers like so:

```yaml
sites:
  - name: Google
    url: https://www.google.com
    expectedStatusCodes:
      - 200
      - 201
      - 404
```
