### DISCUSSION TITLE
Check for custom body response

### DISCUSSION THREAD

**Discussion by fabge** [upptime/upptime#601] [Ideas] [answered]
Currently there exists following method to check for specific error messages in the body:

```yaml
sites:
  - name: Custom down
    url: https://example.com
    __dangerous__body_down: "File not found"
```

We use a software which returns following body when running a query against it's health API:

```bash
{'health': 'GREEN', 'causes': []}
```

The API might also return a 200 response code when there is an error and instead return a different body.
So it would be useful to check for the opposite - e.g. string that *should* exist in the body.
