### DISCUSSION TITLE
Improve documentation for WorkflowSchedule

### DISCUSSION THREAD

**Discussion by Tim-W** [upptime/upptime#641] [Ideas] [answered]
workflowSchedule has a very particular syntax, which I do not recognize on its own. Could we have some more documentation on how this syntax is structured?

**Comment by AnandChowdhary** [comment, marked as answer]
For sure, sorry for the poor documentation! This is what it looks like in the docs currently:

```yaml
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
```

Each key refers to a particular GitHub Actions workflow that Upptime uses. For example, "graphs" corresponds to "Graphs CI" and "updateTemplate" means "Update Template CI". The value for these is the cron expression for when to run it. For example, `uptime: "*/5 * * * *"` means that the "Uptime CI" should run every five minutes.
