### DISCUSSION TITLE
Export the metrics

### DISCUSSION THREAD

**Discussion by 1mfaasj** [upptime/upptime#665] [Q&A]
Hi

Is it possible to export the metrics? Is there an metrics endpoint for instance?
I would like to have some historical data over several years

Thanks in advance

**Comment by AnandChowdhary** [comment]
Good idea! Currently the best way is to use the commit history of the particular file using the GitHub API, but I think an official way to do this is a good next step.

Example: https://api.github.com/repos/upptime/upptime/commits?path=history/wikipedia.yml

**Reply by jonathanstanley** [reply]
Thanks for this! Since monitor is roughly every five minutes, but commits are only once per day, it would be great if all monitor results were fully recorded (perhaps a separate csv)

```yml
results:
  - timestamp: 2022-12-12T23:13:51.285Z
    status: 200
    responseTime: 123
  - timestamp: 2022-12-12T23:18:51.285Z
    status: 200
    responseTime: 321
# ...etc
```
