### DISCUSSION TITLE
Is it possible to rename a site?

### DISCUSSION THREAD

**Discussion by ReenigneArcher** [upptime/upptime#675] [Q&A] [answered]
I would like to rename some sites, without losing the history. Is it possible?

For example:

```yml
sites:
  - name: website
    url: https://www.google.com
```

to...

```yml
sites:
  - name: Google
    url: https://www.google.com
```

If the URL doesn't change will the history remain?
