### DISCUSSION TITLE
Installed it but status-page doesn't show anything

### DISCUSSION THREAD

**Discussion by pluim003** [upptime/upptime#689] [General] [answered]
Tried and tried but probably I'm doing something wrong, but can't figure out what.

Installed it and use in .upptimerc.yml  

  baseUrl: /upptime 

when I visit one of the sites to see the status it shows an empty page:

![afbeelding](https://user-images.githubusercontent.com/67138922/205946921-f2618e17-1454-410d-9c2b-79e8752944fd.png)

And

![afbeelding](https://user-images.githubusercontent.com/67138922/205947071-158e3670-a16a-43a6-98d0-5e39088c7c12.png)

is loading indefinitely but not showing anything. Also weird is that although I changed the text with respect to sample site in .upptimerc.yml it still shows it.

Any clues? Thanx in advance

**Comment by AnandChowdhary** [comment]
Can you share your `.upptimerc.yml` or repository? Seems like a CSS loading issue because of an incorrect base URL, but it looks from the screenshot as though you set everything up correctly!

**Comment by pluim003** [comment]
```
# Change these first
owner: pluim003 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Dick Pluim.com
    url: https://www.dickpluim.com
  - name: KCG
    url: https://www.kunstrijclubgroningen.nl
  - name: Pierced Arrows
    url: https://www.piercedarrows.nl
  - name: Avondklok
    url: https://www.avondklok.eu
  - name: Grafana
    url: <removed this one, have to make that a private one>

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: stats.dickpluim.com
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
```
