### DISCUSSION TITLE
Add cleanup of workflows

### DISCUSSION THREAD

**Discussion by pluim003** [upptime/upptime#691] [Ideas]
After a few days I noticed a long pile of workflows. I looked for an automatic cleanup of it and found one and put it in my workflows-path.
Here's the script:
```
name: workflow run cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: clean workflow runs
        uses: boredland/action-purge-workflow-runs@main
        with:
          days-old: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
