### DISCUSSION TITLE
Change CI Schedule

### DISCUSSION THREAD

**Discussion by seeergiofdez** [upptime/upptime#699] [General] [answered]
Hey, I visited the documentation but haven't found information about the following code:
```
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
```

What does these numbers mean? 

I want to change the CI schedule to make the workflow visit my page every some hours, instead of 5 minutes, which I think is the default time. How could I do it?
I want to make this action so that it **take less build minutes every month**...
Thanks!
