### DISCUSSION TITLE
Customize status website with themes and scripts

### DISCUSSION THREAD

**Discussion by maximousblk** [upptime/upptime#70] [Ideas] [answered]
Is there currently a way I can use a custom website for my status page?

I suppose I can create an api wrapper for github commits and issues, but it would be nice if there was an easy to use interface that can be used by a custom website.

And if a custom website is not feasible, at least ability to customize the website colors using a `themerc.yml` file would be nice too.

**Comment by AnandChowdhary** [comment]
You can create your own status website by using the same API endpoints that the official status website uses. You don't need to create a custom API wrapper for the commits or issues, since our status website also uses the official GitHub API directly, no API wrapper required.

For the colors, I agree completely, I have plans on adding support for theming, custom CSS, and custom JS with plugins for things like Google Analytics. I'll keep this issue open until we release that.

**Comment by gripfastistech** [comment]
I tried various yaml methods to insert an image/graphic/icon file for the monitored sites before the title, using an assets folder within my repo that store the images but kept getting build errors/unexpected string/token, etc.

Would I need to create a seperate json file for each one, then reference the image through it in the yaml file to do this?

It would be easier to "read" the list at a glance by having the .ico files before the titles on the status page.

This may become mute considering future CSS enhancements. Subscribing to this thread.

**Comment by AnandChowdhary** [comment]
I think it's just easier to add an icon feature for each site rather than trying to add an `<img...` in the YAML site title. Can you open a separate issue for "Add support for URL icons"? Then we can show these icons in the README and on the status website.

**Comment by AnandChowdhary** [comment]
I've added a bunch of things that might help you customize the site, but I'll keep this issue open until there is more theme-based customization available. The added features are:

Custom JavaScript file:

```yaml
status-page:
  scripts:
    - src: https://example.com/your-file.js
    - src: https://example.com/your-async-file.js
      async: true
```

Custom stylesheets:

```yaml
status-page:
  links:
    - rel: stylesheet
      href: https://example.com/your-stylesheet.css
```

Custom plain CSS or JS:

```yaml
status-page:
  css: "body { opacity: 0.5 }"
  js: "window.onload = function() { alert("Loaded!") }"
```

**Comment by HalianElf** [comment]
The custom CSS is perfect. The only thing I haven't figured out is the graph colors since they're images. This still for the future customizations or am I just missing something?

**Comment by AnandChowdhary** [comment]
> The only thing I haven't figured out is the graph colors since they're images. This still for the future customizations or am I just missing something?

Yes, this is still something that will be added soon. If it's important, you can use custom CSS with the [`hue-rotate()`](https://www.google.com/search?client=safari&rls=en&q=css+hue+rotate&ie=UTF-8&oe=UTF-8) function to change the colors, as a temporary solution.

**Comment by gripfastistech** [comment]
@HalianElf @AnandChowdhary For the individual service response pages couldn't get a good result using filter:hue-rotate(Xdeg); but this looks pretty rad on a black/dark background, (but looses the text: "Response Time" box):

![filter saturate](https://user-images.githubusercontent.com/53624322/104389535-8b3f5580-54f0-11eb-9c4b-6f33a9bd1918.png)

.chartjs-render-monitor {
	animation: chartjs-render-animation 0.001s;
	filter: saturate(1500);
}

Or if you want the filled area:
![Screenshot_2021-01-12 https gripfastistech github io](https://user-images.githubusercontent.com/53624322/104389899-5aabeb80-54f1-11eb-8f06-d109753a006e.png)

.chartjs-render-monitor {
	animation: chartjs-render-animation 0.001s;
	filter: saturate(1480);
}

Still trying to get similar on the front page status page...

**Comment by HalianElf** [comment]
I ended up just grey scaling the main page 
![image](https://user-images.githubusercontent.com/28244771/104396071-fd776080-5517-11eb-9cea-a1ed8601d580.png)

 and not perfect but got it close to a red like I wanted it for the main graphs 
![image](https://user-images.githubusercontent.com/28244771/104396118-13852100-5518-11eb-9af2-7ceb1b22bb9f.png)

**Reply by FxllenCode** [reply]
@HalianElf  How did you achieve this? Do you mind sharing your code you used in this case? (The dark theme looks great as well!)

Of course this would be great as a built in feature, but for now, your code for the graphs and background would be really helpful! ([I'm surprised you were able to get it working on the main page considering this.](https://github.com/upptime/upptime/discussions/70#discussioncomment-277995))

**Reply by gripfastistech** [reply]
@FxllenCode You could something like this to grayscale it:

article.svelte-uyma2x.svelte-uyma2x.svelte-uyma2x {
	filter: grayscale(100%);
}

**Reply by FxllenCode** [reply]
@gripfastistech Didn't seem to do the job; I think the user above used a more custom solution that just that.

**Reply by FxllenCode** [reply]
Also, 

> article.svelte-uyma2x.svelte-uyma2x.svelte-uyma2x {
> filter: grayscale(100%);
> }


Does not actually change just the graph, it changes the entire status line, as shown below:

![chrome_nFDknEhuXg](https://user-images.githubusercontent.com/40151425/105439464-e8df4a80-5c32-11eb-930d-824d2b030aba.png)

It seems that the graph is combined with the line, and you cannot edit one without the other changing. I don't know if this is intended or not but it doesn't seem right AFAIK. 

cc: @AnandChowdhary

**Reply by gripfastistech** [reply]
@FxllenCode Yeah, that's right. AnandChowdhary is looking into other options, one could always use the api to make a real webapge and do anything you want but myself didn't want to go that far since the basic set-up is already 99.5% awesomesauce. I just changed mine to grayscale also, wish the left border could stay green for "good" status but I realize my expectations are waaaay out in the weeds.

![Screenshot_2021-01-21 Real-time and historical data on system performance (1)](https://user-images.githubusercontent.com/53624322/105440993-7bc0ba80-5c1c-11eb-84aa-9d06c9aecb50.png)

**Reply by HalianElf** [reply]
The CSS I wrote for it is here: https://github.com/HalianElf/css/blob/master/upptime.css
(actually that one makes the graphs blue, the one in my dev folder is the red/pink) It does let the edge keep its status color too.

**Comment by AnandChowdhary** [comment, marked as answer]
Support for themes has been added in [`upptime/status-page@v1.8.0`](https://github.com/upptime/status-page/releases/tag/v1.8.0). Theme can be `light`, `dark`, or `ocean`:

```yaml
status-page:
  theme: "light"
```

| Dark | Ocean |
| - | - |
| ![Screen Shot 2021-01-22 at 20 14 22](https://user-images.githubusercontent.com/2841780/105506420-09b9a580-5cf0-11eb-81d3-2c84f3b945d8.png) | ![Screen Shot 2021-01-22 at 20 16 25](https://user-images.githubusercontent.com/2841780/105506404-045c5b00-5cf0-11eb-89f8-c50ab2f7f98e.png) |

You can create your own themes using CSS variables, using [`dark.css`](https://github.com/upptime/status-page/blob/v1.8.0/static/themes/dark.css), for example as a starting point:

```css
:root {
  --body-background-color: #001716;
  --body-text-color: #f0ffff;
  --card-background-color: #002b29;
  --nav-background-color: #002b29;
  --nav-border-bottom-color: #015450;
}
/* . . . */
```

**Reply by FxllenCode** [reply]
Great, thank you so much, I just added it but this looks better! Is there support for coloring the graph?

**Reply by AnandChowdhary** [reply]
> Is there support for coloring the graph?

Yes, you can use CSS filters using the variable `--graph-filter`. You can also adjust the opacity using `--graph-opacity`.

**Reply by FxllenCode** [reply]
> Yes, you can use CSS filters using the variable `--graph-filter`. You can also adjust the opacity using `--graph-opacity`.

Does that work on the front page as well? Because the graph is part of the actual banned, [this is the outcome.](https://github.com/upptime/upptime/discussions/70#discussioncomment-301154)

**Reply by AnandChowdhary** [reply]
Yes, it will work on the front page. 😄

**Reply by maximousblk** [reply]
> You can create your own themes using CSS variables, using dark.css, for example as a starting point:

how do you add the theme?

I tried doing the following but none worked

```yml
status-website:
  css: "@import url('https://raw.githubusercontent.com/nestdotland/assets/master/css/status.css');"


status-website:
  links:
    - rel: stylesheet
      href: https://raw.githubusercontent.com/nestdotland/assets/master/css/status.css

status-website:
  theme: "https://raw.githubusercontent.com/nestdotland/assets/master/css/status.css"
```
