### DISCUSSION TITLE
Customize CI schedule

### DISCUSSION THREAD

**Discussion by maximousblk** [upptime/upptime#71] [Ideas] [answered]
There seems to be no way to way to change the schedule for the several workflows (`Graphs CI`, `Response Time CI`, etc.). It would be nice if there was.

**Comment by AnandChowdhary** [comment]
I can explore it, what is your use case?

**Comment by AnandChowdhary** [comment]
I don't want people to mess with the individual workflow files because I'd like to keep them in sync when sending updates, but you can, for example, delete "Update Template CI" and make all the changes to `.yml` workflows you want, but this opens you to breaking changes unless you manually update the template when required.

Maybe the easiest thing to do is have an option to run Uptime CI every 10/15/30/etc. min instead of 5 min. We can make this work by still scheduling the workflow every 5 mins, but skipping it based on workflow number modulo (`%`).

If you can tell me about your exact use case and why you want to change the template schedule, I can think of more ideas.

**Comment by maximousblk** [comment]
I don't have a specific use case for me, but here's an example:

Say I wanna run the `Response Time CI` 2 or 4 times a day to see if the load times vary at different times of the day, for example, because of more users in the day but not many users at night. so if the `Response Time CI` only runs at night, we can't catch the stressed response times until a user reports it.

**Comment by maximousblk** [comment]
for how to implement it:

Assuming the following to be the config format:

```yml
owner: "owner"
repo: "repo"

sites:
  - name: Endpoint 1
    url: https://end.point/1

  - name: Endpoint 1
    url: https://end.point/2

status-website:
  # ...

workflows:
  "Graphs CI":
    schedule: '*/5 * * * *'
  "Response Time CI":
    schedule: '*/5 * * * *'
# ...
```

you could update the intervals and update the workflow files in the `Setup CI` workflow?

**Comment by AnandChowdhary** [comment]
Yes, that makes sense, we can add that, and then re-run the CI updates as part of running Update Template CI, because otherwise the changes will be overwritten

**Comment by AnandChowdhary** [comment, marked as answer]
This has been added in [upptime/uptime-monitor@v1.19.0](https://github.com/upptime/uptime-monitor/releases/tag/v1.19.0). I'll update the docs on the site shortly, but you can do this in your `.upptimerc.yml`, these are the default values:

```yaml
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
```
