### DISCUSSION TITLE
gh-pages are broken, may be?

### DISCUSSION THREAD

**Discussion by ijunaid8989** [upptime/upptime#89] [Q&A] [answered]
I followed the https://upptime.js.org/docs/get-started#after-creating-your-repository guide and it was already set to gh-pages but my page looks like this. is that the default behaviour for this? 

https://github.com/ijunaid8989/whowasdown

![image](https://user-images.githubusercontent.com/13561999/100148961-48cda500-2ebf-11eb-8d6b-fd179449c8e1.png)

**Comment by alivenotions** [comment, marked as answer]
This generally happens when the config is a bit wrong.
What do you have in the status-website baseUrl?
```
status-website:
  baseUrl: /repo
```

**Comment by ijunaid8989** [comment]
this is how it looks now

```
# Change these first
owner: ijunaid8989 # Your GitHub username
repo: whowasdown # Your Github repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /repo
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WhoWasDown
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Who was down, do you know?
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

```
