### ISSUE TITLE
monitoring for a keyword

### ISSUE THREAD

**Issue by euro** [upptime/upptime#101]
Sometimes a status of 200 is not enough when custom fail pages are presented to the user. An option for a keyword query would be very helpful.

**Comment by AnandChowdhary** [comment]
This has been added as a feature, but I don't recommend this approach. If you show a custom error page, the HTTP response should not be 200. If you still want to mark a page as "down" or "degraded" by checking for some string in the response body, you can use this:

```yaml
sites:
  - name: Custom down
    url: https://example.com
    __dangerous__body_down: "File not found"
```

In the above example, if the body HTML response includes the string "File not found", the site will be marked as "down". Similarly, you can use `__dangerous__body_degraded` to mark the site as "degraded" instead.
