### ISSUE TITLE
JSON in body is not getting included

### ISSUE THREAD

**Issue by ShivamJoker** [upptime/upptime#102]
I am trying this in my `yml` file as described in the docs, I tried everything but nothing worked it's just sending empty body to the server.
I don't know why, please look into the issue

```yml
  - name: User Login Up
    method: POST
    url: https://untitled-21r9rlkgb6mq.runkit.sh
    headers:
      - "Content-Type: application/json; charset=utf-8"
    body: '{ "password": "hello" }'
```

I also tried quoting the strings but nothing worked in my runkit there is just

```js
// listen for POST requests and respond based on that POSTed data
app.post("/", (req, res) => {

    console.log(req.body);
        
    return res.send({ message: `You posted ${JSON.stringify(req.body)}` });
});
```

It works properly with CURL but is not with this action
<img width="507" alt="image" src="https://user-images.githubusercontent.com/23727670/100846009-02baa780-34a4-11eb-92df-2a1e793df531.png">

Here is what I get in my runkit logs
<img width="381" alt="image" src="https://user-images.githubusercontent.com/23727670/100846141-2a117480-34a4-11eb-87b5-0b99f1641a6a.png">
