### ISSUE TITLE
upptime reports sites as down when using Cloudflare Tunnels, even though they are accessible

### ISSUE THREAD

**Issue by goncalopolido** [upptime/upptime#1079]
**Describe the bug**
I'm using Cloudflare Tunnels (`cloudflared`) to expose some self-hosted services to the internet. All services are online and accessible via browser, but Upptime is reporting them as down.

**To Reproduce**

1. Deploy Upptime with the following config:

```yaml
owner: polido
repo: upptime

sites:
  - name: Chibisafe
    url: https://chibisafe.polido.pt
  - name: clim8
    url: https://clim8.polido.pt
  - name: Uguu
    url: https://uguu.polido.pt
    port: 80
    check: "tcp-ping"

status-website:
  cname: upptime.polido.pt
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/goncalopolido/upptime
```

2. Wait for the scheduled GitHub Actions run
3. Visit the generated status page
4. All sites appear as down

**Expected behavior**
Since the services are up and accessible publicly (via Cloudflare Tunnel), they should be marked as up by Upptime.

**Screenshots**
N/A

**Desktop:**

* OS: Windows 10
* Browser: Google Chrome
* Version: Latest

**Smartphone (please complete the following information):**

* Device: iPhone 15
* IOS: 18.4.1
* Browser: Safari
* Version: Latest

**Additional context**

* All domains point to active Cloudflare Tunnels and are reachable in browser.
* It's possible that `tcp-ping` fails due to Cloudflare not exposing direct IPs.
* Services work fine via HTTPS, so using `http` checks should ideally work.
* Maybe Upptime's IPs are being blocked or challenged by Cloudflare?
* Example of affected URL: [https://chibisafe.polido.pt/](https://chibisafe.polido.pt)
