### ISSUE TITLE
HTTP 403 is reported, CLI curl returns 200

### ISSUE THREAD

**Issue by jieter** [upptime/upptime#226]
**Describe the bug**
Site is reported as down, `HTTP code: 403`, but the site is actually up.
 
**To Reproduce**
1. Add observation.org to `.upptimerc.yml`
```yml
sites:
  - name: observation.org
    url: https://observation.org
```
2. Wait until action is ran.
3. Notice upptime creates an '🛑 observation.org is down'-issue.

**Expected behavior**
HTTP status reported by CLI curl is 200, I would expect upptime to report the same.
```
$ curl -I https://observation.org
HTTP/1.1 200 OK
...
```

**Comment by jayantkatia** [comment]
Seems like this site is filtering out traffic on the basis of  user-agent. Any request with user-agent containing "bot" will return forbidden.
``` shell
$ curl -IA "anything bot" https://observation.org
HTTP/1.1 403 Forbidden
...
```
``` shell
$ curl -IA "anything" https://observation.org
HTTP/1.1 200 OK
...
```
[Uptime monitor](https://github.com/upptime/uptime-monitor) sends "Koj Bot" as its user-agent and is currently not configurable.
@AnandChowdhary Can we make this configurable?

**Comment by jayantkatia** [comment]
@AnandChowdhary, Can we have this as a configurable option in the upcoming releases? I would like to work on this

**Comment by AnandChowdhary** [comment]
Sure, happy to accept a PR!

**Comment by jayantkatia** [comment]
@jieter 
Refer https://github.com/jayantkatia/status/blob/master/.upptimerc.yml#L9
```yml
  - name: observation.org    
    url: https://observation.org
    headers:
      - "User-Agent: <name> uptime"
```
Uptime monitor sets config provided headers using CURL_SETOPT as well.
See https://github.com/upptime/uptime-monitor/blob/master/src/helpers/request.ts#L15 and now https://observation.org has status 'Up'

Tinkering with this issue, i found that config provided headers (User-Agent) will take priority.
