### ISSUE TITLE
GH_PAT is not scoped anywhere in the YAML file, causing severe rate-limiting issues

### ISSUE THREAD

**Issue by FxllenCode** [upptime/upptime#287]
**Please read:**

https://github.com/actions/virtual-environments/issues/2921

**Describe the bug**
Over the last couple of weeks, I have been dealing with extreme rate limiting, to the point where upptime is useless. Turns out `GH_PAT` isn't scoped anywhere on the YAML file, meaning it's easy to hit the rate limit because system tokens have a ratelimit of 1000 while PAT have a limit of 5000. 

**To Reproduce**
1. Have an upptime repo that checks very often, such as:
```yml
workflowSchedule:
  graphs: "/10 * * * *"
  responseTime: "*/10 * * * *"
  staticSite: "0 1 * * *"
  summary: "*/10 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"
```
2. After some time, you will be dealing with rate-limiting. 
**Expected behavior**
The ratelimit is not 1000, it's 5000. 

**Screenshots**

![Code_M6xFkq1Gvc](https://user-images.githubusercontent.com/40151425/111080033-f3032400-84d2-11eb-883f-8354a41e81c2.png)

![chrome_ktpCsnJ5h6](https://user-images.githubusercontent.com/40151425/111080039-f8606e80-84d2-11eb-8e0a-f89db95c205d.png)

(Update removing `GH_PAT`:)

![bCEfdxqTiK](https://user-images.githubusercontent.com/40151425/111080044-fbf3f580-84d2-11eb-8ea2-0ebf80c83459.png)

![WF5T7R4Lgt](https://user-images.githubusercontent.com/40151425/111080066-1201b600-84d3-11eb-9a6d-c5bbbe8aa407.gif)

**Additional context**
The documentation does not explain anything about this:

https://upptime.js.org/docs/get-started#add-repository-secrets

Thank you, I hope for a quick fix. 🙂
