### ISSUE TITLE
Workflow schedule not setting properly

### ISSUE THREAD

**Issue by crstauf** [upptime/upptime#356]
**Describe the bug**
As described elsewhere, I'm going to use `repository_dispatch` events to trigger the _Uptime CI_ workflow. Because I no longer need the workflow to be scheduled for every five minutes, I set `workflowSchedule` in `.upptimerc.yml` to the following:

```yml
status-website:
  workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 6 * * *"
    staticSite: "0 1 * * *"
    summary: "0 0 * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 3 * * *"
    uptime: "0 0 * * *"
```

However this schedule did not carry over to the `response-time.yml` and `uptime.yml` workflow files.

**To Reproduce**
1. Change workflow schedules from default
2. Allow _Setup CI_ workflow to run
3. Check workflow files of workflows with changed schedules

**Expected behavior**
Workflow schedule to match entry in config file.

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA
