### ISSUE TITLE
Fav icons not showing on status page.

### ISSUE THREAD

**Issue by modem7** [upptime/upptime#440]
**Describe the bug**
Fav icons not showing on status page, but are on github.

**To Reproduce**
```
sites:
  - name: Google
    url: https://www.google.com
  - name: Plex
    url: $PLEX_URL
    icon: https://favicons.githubusercontent.com/plex.tv
    asignee: modem7
    expectedStatusCodes:
      - 403
      - 404
  - name: Wiki
    url: https://omegawiki.modem7.com
    asignee: modem7
    expectedStatusCodes:
      - 403
      - 404
  - name: Overseer
    url: $OVERSEER_URL
    icon: https://github.com/sct/overseerr/blob/develop/public/favicon-32x32.png
    asignee: modem7
    expectedStatusCodes:
      - 403
      - 404
  - name: Ombi
    url: $OMBI_URL
    icon: https://github.com/Ombi-app/Ombi/blob/develop/src/Ombi/wwwroot/images/favicon/favicon-32x32.png
    asignee: modem7
    expectedStatusCodes:
      - 403
      - 404
  - name: Grafana
    url: $GRAFANA_URL
    icon: https://github.com/grafana/grafana/blob/main/public/img/fav32.png
    asignee: modem7
    expectedStatusCodes:
      - 403
      - 404
```

**Expected behavior**
For fav icons to show on both. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4349962/133003502-3407fde5-bc6e-4fdb-b5da-7ce848111d52.png)
