### ISSUE TITLE
Can't change Status Page Footer

### ISSUE THREAD

**Issue by LeonTheDev-io** [upptime/upptime#464]
**Describe the bug**
When I add a ` i18n:
  footer: Test` the footer does not change, and still says "This page is open source, powered by Upptime"

**.upptimerc.yml**
```
owner: LeonTheDev-io
repo: UpTimeChecker
sites:
  - name: EGF Appeals
    url: https://egf-appeals.netlify.app
status-website: 
  name: Status
  baseUrl: /UpTimeChecker
  i18n:
  footer: Test
```

Did I just do something wrong or is it a bug?

**Comment by AnandChowdhary** [comment]
Yes, your syntax is incorrect (the space before `i18n` is unnecessary):

```yaml
owner: LeonTheDev-io
repo: UpTimeChecker
sites:
  - name: EGF Appeals
    url: https://egf-appeals.netlify.app
status-website: 
  name: Status
  baseUrl: /UpTimeChecker
i18n:
  footer: Test
```
