### ISSUE TITLE
A lot of false positive cases - Upttime says sites are down but they are not!

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [upptime/upptime#553]
I noticed that most of the time upptime bot will incorrectly report a problem with my website(s) that it's down but when I got and visit it I see it works just fine 

So how to solve this little bug? I use in my config:
```yml
  - name: Example
    url: https://example.org
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
```
and here is an example: https://github.com/EsmailELBoBDev2/upptime/issues/884

It's really annoying especially when I enabled email notifications so literally my inbox get filled with so many "not working" websites to figure out after some minutes it's just working fine
