### ISSUE TITLE
Summary CI failing due to missing action

### ISSUE THREAD

**Issue by ScottGuymer** [upptime/upptime#559]
**Describe the bug**
Summary CI workflow is failing due to a missing action 

```
 Unable to resolve actions. Repository not found: koj-co/readme-repos-list.
```

Looks like this action has been moved to https://github.com/AnandChowdhary/readme-repos-list and archived 

**To Reproduce**
1. Make new repo from template
2. Observe that Summary CI workflow fails

**Expected behavior**
Workflow CI workflow should run correctly 

**Screenshots**
![image](https://user-images.githubusercontent.com/956825/168230795-581810e7-206a-43a7-91b8-de43e2a02c21.png)

**Workflow File**

This is the workflow file that is failing

```yaml

# This file was generated by upptime/uptime-monitor@v1.26.4
#
# ===============================
# Do not edit this file directly!
# ===============================
#
# Your changes will be overwritten when the template updates (daily)
# Instead, change your .upptimerc.yml configuration: https://upptime.js.org/docs

name: Summary CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [summary]
  workflow_dispatch:
jobs:
  release:
    name: Generate README
    runs-on: [self-hosted, linux, X64, philips]
    container: node:16

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Update summary in README
        uses: upptime/uptime-monitor@v1.26.4
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Run readme-repos-list
        uses: koj-co/readme-repos-list@master
        with:
          token: ${{ secrets.GH_PAT }}
          query: "topic:upptime"
          size: 20
          max: 1000
          one-per-owner: true
```
