### ISSUE TITLE
Always says it’s down if site uses self-signed certificate

### ISSUE THREAD

**Issue by SJang1** [upptime/upptime#57]
It always says it’s down when site cert is not trusted.
It needs to have settings like {insecure=true|false} for some sites like mine

**Comment by AnandChowdhary** [comment]
Can you share a link to your site? Let me see why it doesn't like your certificate. :)

**Comment by SJang1** [comment]
here is the link, for browsers it won't able to connect because of HSTS of .dev domain prelod. It is able to connect by curl with insecure option.

https://desktop.sjang.dev:2364/{api-key-is-secret}

**Comment by AnandChowdhary** [comment]
This is now fixed, you can use the `__dangerous__insecure` configuration key in your sites:

```yaml
sites:
  method: GET
  url: https://desktop.sjang.dev:2364
  __dangerous__insecure: true
```

Settings the `__dangerous__insecure` option sets `SSL_VERIFYPEER` as `false`. I've added the `__dangerous__` prefix to this key to remind people that they should only be setting this as `true` if they're sure about it!

**Comment by wtfpeter** [comment]
Hi @AnandChowdhary and sorry for reviving this issue. Can you maybe check if this flag also makes upptime ignore certificate name mismatches? I have a special case where I can't change the certificate but still would like to test availability and the check endpoint step in the uptime action is giving me `Current status undefined down 2020-11-23T13:13:49.000Z`

**Comment by SJang1** [comment]
`SSL_VERIFYHOST` might be help for that, not only `VERIFYPEER`
@AnandChowdhary

**Comment by AnandChowdhary** [comment]
Thanks, @SJang1! Let me add an option for that as well. 😄

**Comment by AnandChowdhary** [comment]
@wtfpeter, you can now add the `__dangerous__disable_verify_host` option:

```yaml
sites:
  method: GET
  url: https://desktop.sjang.dev:2364
  __dangerous__disable_verify_host: true
```
