### ISSUE TITLE
 Error on Generate Site step (w/ GitHub Organizations)

### ISSUE THREAD

**Issue by fabge** [upptime/upptime#581]
I have set up the upptime repository following the Getting started guide, using the template mechanism inside a GitHub Organization.
Everything works as expected, except the `Generate site` step.
In this step it seems that no output is produced, the only output is:

```
Run upptime/uptime-monitor@v1.27.0
  with:
    command: site
  env:
    GH_PAT: ***
```

Comparing this to a setup in a repository outside a GitHub Organizations, there is a lot more output.

The following deploy step also shows that there where no files generated:

```
  nothing to commit, working tree clean
```
