### ISSUE TITLE
Fav icons not showing when using GitHub secret for URL

### ISSUE THREAD

**Issue by HDVinnie** [upptime/upptime#606]
**Describe the bug**
Fav icons not showing when using GitHub secret for URL to favicon like `https://www.google.com/favicon.ico`

**To Reproduce**
```
sites:
  - name: BHD
    url: $BHD
    icon: $BHD_ICON
  - name: BLU
    url: $BLU
    icon: $BLU_ICON
  - name: PTP
    url: $PTP
    icon: $PTP_ICON
```

**Expected behavior**
Icons to load
