### ISSUE TITLE
Incorrect status of websites

### ISSUE THREAD

**Issue by callmeurpapa** [upptime/upptime#625]
hi all

Some sites are displayed as not working.

Tried: 

- https/http
- different pages
- added protocols

**dash:**

https://callmeurpapa.github.io/uptime

**repo:**

https://github.com/callmeurpapa/uptime

**Comment by AnandChowdhary** [comment]
You can see the errors for example in https://github.com/callmeurpapa/uptime/runs/7574182239?check_suite_focus=true:

```
Got an error (on error) [Error: SSL peer certificate or SSH remote key was not OK]
```

or 

```
Got an error (on error) [Error: Timeout was reached]
```

Could it be that GitHub's servers are unable able to access this since because of Russia-related sanctions or maybe the site itself doesn't respond when it sees a request from GitHub's IP addresses?

**Comment by callmeurpapa** [comment]
Thx for fast feedback!

Is there any way I can turn off SSL verification?

**Comment by AnandChowdhary** [comment]
I'm not sure if this will fix it, but it's worth a shot, you can use the `__dangerous__insecure` property: https://upptime.js.org/docs/configuration/#self-signed-ssl-certificates

**Comment by callmeurpapa** [comment]
I think the reason on DDOS protection. Is there any way I can shorten the query intervals or some other solution?

**Comment by AnandChowdhary** [comment]
Not that I can think of, no. Maybe it's a good idea to add a configuration param for delay between sites?

**Comment by callmeurpapa** [comment]
Let me knowm please, how can I do that?

> Not that I can think of, no. Maybe it's a good idea to add a configuration param for delay between sites?

**Comment by AnandChowdhary** [comment]
You can now add a `delay` option in your `.upptimerc.yml` configuration file:

```yaml
delay: 2000 # Delay of 2 seconds between sites
```

**Comment by callmeurpapa** [comment]
into block ```workflowSchedule``` ?

**Comment by AnandChowdhary** [comment]
No, this will be in your `.upptimerc.yml` file: https://upptime.js.org/docs/configuration/

**Comment by callmeurpapa** [comment]
Thats right! I mean like that:?

```
sites:
  - name: SITE
    url: http://site.ru
    __dangerous__disable_verify_peer: true
    **delay: 2000 # Delay of 2 seconds between sites**
```

or:

```
workflowSchedule:
  graphs: "0 */6 * * *"
  responseTime: "10 */6 * * *"
  staticSite: "20 */6 * * *"
  summary: "30 */6 * * *"
  updateTemplate: "0 0 * * *"
  updates: "40 */6 * * *"
  uptime: "*/5 * * * *"
  **delay: 2000 # Delay of 2 seconds between sites**
```
or

```
status-website:
  baseUrl: uptime
  logoUrl: https://www.sibur.ru/local/templates/main/assets/images/Fav-ru.jpg
  name: Upptime
  **delay: 2000 # Delay of 2 seconds between sites**
```

**Comment by AnandChowdhary** [comment]
Like so:

```yaml
delay: 2000
sites:
  - name: SITE
    url: http://site.ru
    __dangerous__disable_verify_peer: true
status-website:
  baseUrl: uptime
  logoUrl: https://www.sibur.ru/local/templates/main/assets/images/Fav-ru.jpg
  name: Upptime
```
