### ISSUE TITLE
Customize status website with themes and scripts

### ISSUE THREAD

**Issue by maximousblk** [upptime/upptime#70]
Is there currently a way I can use a custom website for my status page?

I suppose I can create an api wrapper for github commits and issues, but it would be nice if there was an easy to use interface that can be used by a custom website.

And if a custom website is not feasible, at least ability to customize the website colors using a `themerc.yml` file would be nice too.

**Comment by AnandChowdhary** [comment]
You can create your own status website by using the same API endpoints that the official status website uses. You don't need to create a custom API wrapper for the commits or issues, since our status website also uses the official GitHub API directly, no API wrapper required.

For the colors, I agree completely, I have plans on adding support for theming, custom CSS, and custom JS with plugins for things like Google Analytics. I'll keep this issue open until we release that.

**Comment by gripfastistech** [comment]
I tried various yaml methods to insert an image/graphic/icon file for the monitored sites before the title, using an assets folder within my repo that store the images but kept getting build errors/unexpected string/token, etc.

Would I need to create a seperate json file for each one, then reference the image through it in the yaml file to do this?

It would be easier to "read" the list at a glance by having the .ico files before the titles on the status page.

This may become mute considering future CSS enhancements. Subscribing to this thread.

**Comment by AnandChowdhary** [comment]
I think it's just easier to add an icon feature for each site rather than trying to add an `<img...` in the YAML site title. Can you open a separate issue for "Add support for URL icons"? Then we can show these icons in the README and on the status website.

**Comment by AnandChowdhary** [comment]
I've added a bunch of things that might help you customize the site, but I'll keep this issue open until there is more theme-based customization available. The added features are:

Custom JavaScript file:

```yaml
status-page:
  scripts:
    - src: https://example.com/your-file.js
    - src: https://example.com/your-async-file.js
      async: true
```

Custom stylesheets:

```yaml
status-page:
  links:
    - rel: stylesheet
      href: https://example.com/your-stylesheet.css
```

Custom plain CSS or JS:

```yaml
status-page:
  css: "body { opacity: 0.5 }"
  js: "window.onload = function() { alert("Loaded!") }"
```
