### ISSUE TITLE
Cloudflare http error codes still count as up

### ISSUE THREAD

**Issue by EmnichtdaYT** [upptime/upptime#881]
**Describe the bug**
When a site behind the cloudflare proxy is down, cloudflare returns non-standard http status codes. By default, upptime still counts these status codes as if the website were up.

To reproduce, I used the bare minimum configuration:
```yml
sites:
  - name: Behind cloudflare example
    url: https://www.example.at
```

**Expected behavior**
I believe upptime should count these cloudflare error codes as down by default.

**Additional context**
Wikipedia has a good summary of these status codes. [https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Cloudflare](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Cloudflare)
