### ISSUE TITLE
Status Website looks different with no CSS and nothing being shown in Live-Status

### ISSUE THREAD

**Issue by harsh778** [upptime/upptime#98]
Hi!
First of all, great work on the Upptime. It is great! 
I was having a few issues while following the get-started doc (https://upptime.js.org/docs/get-started).
1. It asked me to go to the Github Pages setting and change the source to gh-pages. When I changed that and saved the setting, it said, "The CNAME demo.upptime.js.org is already taken. Check out https://docs.github.com/articles/troubleshooting-custom-domains#cname-errors for more information."
2. Also, the site is maybe published at https://harshsinghal.me/harshsinghal.me-status/ but it looks that there is no CSS. Secondly, the live status is just loading and nothing is being shown.
My current .upptimerc.yml is -

```
owner: harsh778 
repo: harshsinghal.me-status 

sites:
  - name: Harsh Vardhan Singhal
    url: https://harshsinghal.me

status-website:
  baseUrl: /harshsinghal.me-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Keeper for harshsinghal.me
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
```

Repo Name: harshsinghal.me/status ( I want to use this status monitor to track the status of my personal website https://harshsinghal.me)
Any help will be greatly appreciated.
Thanks
Harsh
