### ISSUE TITLE
How to set the body of a POST for a site

### ISSUE THREAD

**Issue by metrue** [upptime/upptime#99]
There's a doc about how to do the `POST` but did not include the body https://upptime.js.org/docs/configuration#http-verbs
So how can I post a JSON payload to a endpoint?

**Comment by AnandChowdhary** [comment]
This has been added:

```yaml
sites:
  method: POST
  url: https://example.com
  headers:
    - "Content-Type: application/json"
  body: '{ "name": "Anand" }'
```

You can put any string in `body` based on your content-type header. 😄
